// ===== 英语学习数据 =====

const VOCAB_DATA = [
  // ---- 动物 animals ----
  { id: 1,  en: "cat",      zh: "猫",     category: "animals",  emoji: "🐱", difficulty: 1 },
  { id: 2,  en: "dog",      zh: "狗",     category: "animals",  emoji: "🐶", difficulty: 1 },
  { id: 3,  en: "fish",     zh: "鱼",     category: "animals",  emoji: "🐟", difficulty: 1 },
  { id: 4,  en: "bird",     zh: "鸟",     category: "animals",  emoji: "🐦", difficulty: 1 },
  { id: 5,  en: "rabbit",   zh: "兔子",   category: "animals",  emoji: "🐰", difficulty: 1 },
  { id: 6,  en: "duck",     zh: "鸭子",   category: "animals",  emoji: "🦆", difficulty: 1 },
  { id: 7,  en: "pig",      zh: "猪",     category: "animals",  emoji: "🐷", difficulty: 1 },
  { id: 8,  en: "bear",     zh: "熊",     category: "animals",  emoji: "🐻", difficulty: 2 },
  { id: 9,  en: "monkey",   zh: "猴子",   category: "animals",  emoji: "🐵", difficulty: 2 },
  { id: 10, en: "elephant", zh: "大象",   category: "animals",  emoji: "🐘", difficulty: 2 },

  // ---- 颜色 colors ----
  { id: 11, en: "red",      zh: "红色",   category: "colors",   emoji: "🔴", difficulty: 1 },
  { id: 12, en: "blue",     zh: "蓝色",   category: "colors",   emoji: "🔵", difficulty: 1 },
  { id: 13, en: "green",    zh: "绿色",   category: "colors",   emoji: "🟢", difficulty: 1 },
  { id: 14, en: "yellow",   zh: "黄色",   category: "colors",   emoji: "🟡", difficulty: 1 },
  { id: 15, en: "pink",     zh: "粉色",   category: "colors",   emoji: "🩷", difficulty: 1 },
  { id: 16, en: "orange",   zh: "橙色",   category: "colors",   emoji: "🟠", difficulty: 1 },
  { id: 17, en: "white",    zh: "白色",   category: "colors",   emoji: "⚪", difficulty: 1 },
  { id: 18, en: "black",    zh: "黑色",   category: "colors",   emoji: "⚫", difficulty: 1 },
  { id: 19, en: "purple",   zh: "紫色",   category: "colors",   emoji: "🟣", difficulty: 2 },
  { id: 20, en: "brown",    zh: "棕色",   category: "colors",   emoji: "🟤", difficulty: 2 },

  // ---- 数字 numbers ----
  { id: 21, en: "one",      zh: "一 (1)",  category: "numbers",  emoji: "1️⃣", difficulty: 1 },
  { id: 22, en: "two",      zh: "二 (2)",  category: "numbers",  emoji: "2️⃣", difficulty: 1 },
  { id: 23, en: "three",    zh: "三 (3)",  category: "numbers",  emoji: "3️⃣", difficulty: 1 },
  { id: 24, en: "four",     zh: "四 (4)",  category: "numbers",  emoji: "4️⃣", difficulty: 1 },
  { id: 25, en: "five",     zh: "五 (5)",  category: "numbers",  emoji: "5️⃣", difficulty: 1 },
  { id: 26, en: "six",      zh: "六 (6)",  category: "numbers",  emoji: "6️⃣", difficulty: 1 },
  { id: 27, en: "seven",    zh: "七 (7)",  category: "numbers",  emoji: "7️⃣", difficulty: 1 },
  { id: 28, en: "eight",    zh: "八 (8)",  category: "numbers",  emoji: "8️⃣", difficulty: 1 },
  { id: 29, en: "nine",     zh: "九 (9)",  category: "numbers",  emoji: "9️⃣", difficulty: 1 },
  { id: 30, en: "ten",      zh: "十 (10)", category: "numbers",  emoji: "🔟", difficulty: 1 },

  // ---- 食物 food ----
  { id: 31, en: "apple",    zh: "苹果",   category: "food",     emoji: "🍎", difficulty: 1 },
  { id: 32, en: "banana",   zh: "香蕉",   category: "food",     emoji: "🍌", difficulty: 1 },
  { id: 33, en: "milk",     zh: "牛奶",   category: "food",     emoji: "🥛", difficulty: 1 },
  { id: 34, en: "bread",    zh: "面包",   category: "food",     emoji: "🍞", difficulty: 1 },
  { id: 35, en: "egg",      zh: "鸡蛋",   category: "food",     emoji: "🥚", difficulty: 1 },
  { id: 36, en: "rice",     zh: "米饭",   category: "food",     emoji: "🍚", difficulty: 1 },
  { id: 37, en: "cake",     zh: "蛋糕",   category: "food",     emoji: "🎂", difficulty: 1 },
  { id: 38, en: "water",    zh: "水",     category: "food",     emoji: "💧", difficulty: 1 },
  { id: 39, en: "candy",    zh: "糖果",   category: "food",     emoji: "🍬", difficulty: 1 },
  { id: 40, en: "cookie",   zh: "饼干",   category: "food",     emoji: "🍪", difficulty: 1 },

  // ---- 家庭 family ----
  { id: 41, en: "mom",      zh: "妈妈",   category: "family",   emoji: "👩", difficulty: 1 },
  { id: 42, en: "dad",      zh: "爸爸",   category: "family",   emoji: "👨", difficulty: 1 },
  { id: 43, en: "sister",   zh: "姐姐/妹妹", category: "family", emoji: "👧", difficulty: 1 },
  { id: 44, en: "brother",  zh: "哥哥/弟弟", category: "family", emoji: "👦", difficulty: 1 },
  { id: 45, en: "baby",     zh: "宝宝",   category: "family",   emoji: "👶", difficulty: 1 },
  { id: 46, en: "family",   zh: "家庭",   category: "family",   emoji: "👨‍👩‍👧‍👦", difficulty: 2 },
  { id: 47, en: "grandpa",  zh: "爷爷",   category: "family",   emoji: "👴", difficulty: 2 },
  { id: 48, en: "grandma",  zh: "奶奶",   category: "family",   emoji: "👵", difficulty: 2 },
  { id: 49, en: "friend",   zh: "朋友",   category: "family",   emoji: "🤝", difficulty: 2 },
  { id: 50, en: "teacher",  zh: "老师",   category: "family",   emoji: "👩‍🏫", difficulty: 2 },

  // ---- 身体 body ----
  { id: 51, en: "hand",     zh: "手",     category: "body",     emoji: "✋", difficulty: 1 },
  { id: 52, en: "eye",      zh: "眼睛",   category: "body",     emoji: "👁️", difficulty: 1 },
  { id: 53, en: "nose",     zh: "鼻子",   category: "body",     emoji: "👃", difficulty: 1 },
  { id: 54, en: "mouth",    zh: "嘴巴",   category: "body",     emoji: "👄", difficulty: 1 },
  { id: 55, en: "ear",      zh: "耳朵",   category: "body",     emoji: "👂", difficulty: 1 },
  { id: 56, en: "head",     zh: "头",     category: "body",     emoji: "🗣️", difficulty: 1 },
  { id: 57, en: "foot",     zh: "脚",     category: "body",     emoji: "🦶", difficulty: 1 },
  { id: 58, en: "face",     zh: "脸",     category: "body",     emoji: "😊", difficulty: 1 },
  { id: 59, en: "hair",     zh: "头发",   category: "body",     emoji: "💇", difficulty: 1 },
  { id: 60, en: "tooth",    zh: "牙齿",   category: "body",     emoji: "🦷", difficulty: 2 },

  // ---- 问候 greetings ----
  { id: 61, en: "hello",    zh: "你好",   category: "greetings", emoji: "👋", difficulty: 1 },
  { id: 62, en: "goodbye",  zh: "再见",   category: "greetings", emoji: "👋", difficulty: 1 },
  { id: 63, en: "thank you", zh: "谢谢",  category: "greetings", emoji: "🙏", difficulty: 1 },
  { id: 64, en: "sorry",    zh: "对不起", category: "greetings", emoji: "😔", difficulty: 1 },
  { id: 65, en: "please",   zh: "请",     category: "greetings", emoji: "🤲", difficulty: 1 },
  { id: 66, en: "yes",      zh: "是的",   category: "greetings", emoji: "👍", difficulty: 1 },
  { id: 67, en: "no",       zh: "不是",   category: "greetings", emoji: "👎", difficulty: 1 },
  { id: 68, en: "good morning", zh: "早上好", category: "greetings", emoji: "🌅", difficulty: 1 },
  { id: 69, en: "good night",   zh: "晚安",   category: "greetings", emoji: "🌙", difficulty: 1 },
  { id: 70, en: "how are you",  zh: "你好吗", category: "greetings", emoji: "😊", difficulty: 2 },

  // ---- 日常短语 phrases ----
  { id: 71, en: "I want",   zh: "我想要", category: "phrases",  emoji: "🙋", difficulty: 1 },
  { id: 72, en: "this is",  zh: "这是",   category: "phrases",  emoji: "👉", difficulty: 1 },
  { id: 73, en: "I like",   zh: "我喜欢", category: "phrases",  emoji: "❤️", difficulty: 1 },
  { id: 74, en: "I have",   zh: "我有",   category: "phrases",  emoji: "🤲", difficulty: 1 },
  { id: 75, en: "let's go", zh: "走吧",   category: "phrases",  emoji: "🏃", difficulty: 1 },
  { id: 76, en: "come on",  zh: "来吧",   category: "phrases",  emoji: "👋", difficulty: 1 },
  { id: 77, en: "look at",  zh: "看",     category: "phrases",  emoji: "👀", difficulty: 2 },
  { id: 78, en: "I am",     zh: "我是",   category: "phrases",  emoji: "🙋", difficulty: 1 },
  { id: 79, en: "it is",    zh: "它是",   category: "phrases",  emoji: "👉", difficulty: 1 },
  { id: 80, en: "very good", zh: "非常好", category: "phrases",  emoji: "👏", difficulty: 1 },
];

// 分类元数据
const CATEGORIES = {
  animals:  { name: "动物", emoji: "🐾", color: "#FF6B6B" },
  colors:   { name: "颜色", emoji: "🎨", color: "#4ECDC4" },
  numbers:  { name: "数字", emoji: "🔢", color: "#FFE66D" },
  food:     { name: "食物", emoji: "🍎", color: "#FF8E53" },
  family:   { name: "家庭", emoji: "👨‍👩‍👧", color: "#A29BFE" },
  body:     { name: "身体", emoji: "🖐️", color: "#FD79A8" },
  greetings:{ name: "问候", emoji: "👋", color: "#00B894" },
  phrases:  { name: "短语", emoji: "💬", color: "#0984E3" },
};

// 每日句子数据
const SENTENCE_DATA = [
  { id: 1,  en: "I have a cat.",        zh: "我有一只猫。",       emoji: "🐱", vocabIds: [74, 1] },
  { id: 2,  en: "This is red.",         zh: "这是红色的。",       emoji: "🔴", vocabIds: [72, 11] },
  { id: 3,  en: "I want milk.",         zh: "我想要牛奶。",       emoji: "🥛", vocabIds: [71, 33] },
  { id: 4,  en: "I like bananas.",      zh: "我喜欢香蕉。",       emoji: "🍌", vocabIds: [73, 32] },
  { id: 5,  en: "This is a dog.",       zh: "这是一只狗。",       emoji: "🐶", vocabIds: [72, 2] },
  { id: 6,  en: "I have two eyes.",     zh: "我有两只眼睛。",     emoji: "👁️", vocabIds: [74, 22, 52] },
  { id: 7,  en: "Good morning, mom!",   zh: "早上好，妈妈！",     emoji: "🌅", vocabIds: [68, 41] },
  { id: 8,  en: "I like cake.",         zh: "我喜欢蛋糕。",       emoji: "🎂", vocabIds: [73, 37] },
  { id: 9,  en: "This is a bird.",      zh: "这是一只鸟。",       emoji: "🐦", vocabIds: [72, 4] },
  { id: 10, en: "I have five fingers.", zh: "我有五根手指。",     emoji: "🖐️", vocabIds: [74, 25, 51] },
  { id: 11, en: "Hello, friend!",       zh: "你好，朋友！",       emoji: "👋", vocabIds: [61, 49] },
  { id: 12, en: "I want water.",        zh: "我想要水。",         emoji: "💧", vocabIds: [71, 38] },
  { id: 13, en: "This is blue.",        zh: "这是蓝色的。",       emoji: "🔵", vocabIds: [72, 12] },
  { id: 14, en: "I have a rabbit.",     zh: "我有一只兔子。",     emoji: "🐰", vocabIds: [74, 5] },
  { id: 15, en: "Good night, dad.",     zh: "晚安，爸爸。",       emoji: "🌙", vocabIds: [69, 42] },
  { id: 16, en: "I like rice.",         zh: "我喜欢米饭。",       emoji: "🍚", vocabIds: [73, 36] },
  { id: 17, en: "This is a fish.",      zh: "这是一条鱼。",       emoji: "🐟", vocabIds: [72, 3] },
  { id: 18, en: "I have one nose.",     zh: "我有一个鼻子。",     emoji: "👃", vocabIds: [74, 21, 53] },
  { id: 19, en: "Thank you!",           zh: "谢谢！",             emoji: "🙏", vocabIds: [63] },
  { id: 20, en: "I want candy.",        zh: "我想要糖果。",       emoji: "🍬", vocabIds: [71, 39] },
  { id: 21, en: "This is green.",       zh: "这是绿色的。",       emoji: "🟢", vocabIds: [72, 13] },
  { id: 22, en: "I have a sister.",     zh: "我有一个妹妹。",     emoji: "👧", vocabIds: [74, 43] },
  { id: 23, en: "Let's go!",            zh: "走吧！",             emoji: "🏃", vocabIds: [75] },
  { id: 24, en: "I like apples.",       zh: "我喜欢苹果。",       emoji: "🍎", vocabIds: [73, 31] },
  { id: 25, en: "This is a monkey.",    zh: "这是一只猴子。",     emoji: "🐵", vocabIds: [72, 9] },
  { id: 26, en: "I have bread.",        zh: "我有面包。",         emoji: "🍞", vocabIds: [74, 34] },
  { id: 27, en: "I am happy.",          zh: "我很开心。",         emoji: "😊", vocabIds: [78] },
  { id: 28, en: "Very good!",           zh: "非常好！",           emoji: "👏", vocabIds: [80] },
  { id: 29, en: "I like yellow.",       zh: "我喜欢黄色。",       emoji: "🟡", vocabIds: [73, 14] },
  { id: 30, en: "This is a baby.",      zh: "这是一个宝宝。",     emoji: "👶", vocabIds: [72, 45] },
];

// 成就定义
const ACHIEVEMENTS = [
  { id: "first_word",    name: "初学者",     desc: "学会第一个单词",   emoji: "🌱", condition: (s) => s.learnedWords >= 1 },
  { id: "ten_words",     name: "小有进步",   desc: "学会10个单词",     emoji: "🌿", condition: (s) => s.learnedWords >= 10 },
  { id: "fifty_words",   name: "词汇达人",   desc: "学会50个单词",     emoji: "🌳", condition: (s) => s.learnedWords >= 50 },
  { id: "all_words",     name: "词汇大师",   desc: "学会全部80个单词", emoji: "🏆", condition: (s) => s.learnedWords >= 80 },
  { id: "first_sentence",name: "句子里",     desc: "学会第一句话",     emoji: "📖", condition: (s) => s.learnedSentences >= 1 },
  { id: "ten_sentences", name: "小演讲家",   desc: "学会10句话",       emoji: "🎤", condition: (s) => s.learnedSentences >= 10 },
  { id: "streak_3",      name: "三天坚持",   desc: "连续学习3天",      emoji: "🔥", condition: (s) => s.streak >= 3 },
  { id: "streak_7",      name: "一周达人",   desc: "连续学习7天",      emoji: "💪", condition: (s) => s.streak >= 7 },
  { id: "streak_30",     name: "月度之星",   desc: "连续学习30天",     emoji: "🌟", condition: (s) => s.streak >= 30 },
  { id: "first_quiz",    name: "勇敢尝试",   desc: "完成第一次听力练习", emoji: "👂", condition: (s) => s.quizzesDone >= 1 },
  { id: "quiz_10",       name: "听力高手",   desc: "完成10次听力练习",  emoji: "🎧", condition: (s) => s.quizzesDone >= 10 },
  { id: "first_challenge",name: "挑战者",    desc: "完成第一次闯关",   emoji: "🎮", condition: (s) => s.challengesDone >= 1 },
  { id: "perfect_match", name: "完美配对",   desc: "配对游戏全对",     emoji: "✨", condition: (s) => s.perfectMatch >= 1 },
  { id: "stars_10",      name: "星星收集者", desc: "获得10颗星星",     emoji: "⭐", condition: (s) => s.stars >= 10 },
  { id: "stars_50",      name: "星星猎人",   desc: "获得50颗星星",     emoji: "🌠", condition: (s) => s.stars >= 50 },
  { id: "cat_lover",     name: "猫咪爱好者", desc: "学会所有动物单词", emoji: "🐱", condition: (s) => s.categoryComplete?.animals },
];
